const lists = [
  [
    'A Boy\'s Name',
    'U.S. Cities',
    'Things That Are Cold',
    'School Supplies',
    'Pro Sports Teams',
    'Insects',
    'Breakfast Foods',
    'Furniture',
    'TV Shows',
    'Things Foind In The Ocean',
    'Presidents',
    'Product Names',
  ],
  [
    'Vegetables',
    'States',
    'Things You Throw Away',
    'Occupations',
    'Appliances',
    'Cartoon Characters',
    'Types of Drinks',
    'Musical Groups',
    'Store Names',
    'Things At A Football Game',
    'Trees',
    'Personality Traits',
  ],
  [
    'Articles Of Clothing',
    'Desserts',
    'Car Parts',
    'Things Found On A Map',
    'Athletes',
    '4-Letter Words',
    'Items In A Refrigerator',
    'Farm Animals',
    'Street Names',
    'Things At The Beach',
    'Colors',
    'Tools',
  ],
  [
    'Sports',
    'Song Titles',
    'Parts Of The Body',
    'Ethnic Foods',
    'Things You Shout',
    'Birds',
    'A Girl\'s Name',
    'Ways To Get From Here To There',
    'Items In A Kitchen',
    'Villains/Monsters',
    'Flowers',
    'Things You Replace',
  ],
  ['', '', '', '', '', '', '', '', '', '', '', ''],
  ['', '', '', '', '', '', '', '', '', '', '', ''],
  ['', '', '', '', '', '', '', '', '', '', '', ''],
  ['', '', '', '', '', '', '', '', '', '', '', ''],
  ['', '', '', '', '', '', '', '', '', '', '', ''],
  ['', '', '', '', '', '', '', '', '', '', '', ''],
  ['', '', '', '', '', '', '', '', '', '', '', ''],
  ['', '', '', '', '', '', '', '', '', '', '', ''],
];

export default lists;
